import Head from "next/head";
import { useState, useEffect, useRef } from "react";
import Header from "@/components/Header";
import Intro from "@/components/Intro";
import Projects from "@/components/Projects";
import About from "@/components/About";
import ContactForm from "@/components/ContactForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-1 md:grid-cols-2 text-white">
        <div className="flex flex-col justify-between p-8 h-screen md:w-3/4">
          <Header />
          <Intro />
          <p className="font-Fasthand text-4xl">Thanks!</p>
        </div>
        <div className="flex-1 md:overflow-y-hidden">
          <div className="md:overflow-y-scroll md:h-screen p-8 md:px-16">
            <Projects />
            <About />
            <div id="contact" className="space-y-4 py-8">
              <h3 className="text-gray text-2xl font-bold">Contact Me</h3>
              <p className="text-lg">
                Please do hit me up for any collaboration or job offer I&apos;d
                be very glad to discuss with you.
              </p>
              <ContactForm />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
